source/install-atlas-cli.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-21794)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-21794/install-atlas-cli/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624cb1580fdfea9c37bd85c6)
in addition to the changes requested in the Jira, I changed the location of the PGP keys based on https://jira.mongodb.org/browse/DOCS-15195. Did a quick curl and confirmed that the keys are available at the new location.
@sarahsimpers for visibility

DOCSP-21794: update atlascli instructions

---

source/connect-atlas-cli.txt

[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6262dfe20fdfea9c3727a32f)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-22150)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22150/connect-atlas-cli/)
Removes a line from the note on how to fix potential issues with the config file. It is not necessary to be on the access list to use the atlas auth login command.

(DOCSP-22150) Removes line re: need to be on access list for auth login

---

source/connect-atlas-cli.txt

[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6286561155f596c31d3167a2)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-22658)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22658/connect-atlas-cli/#follow-these-steps)
The --skipConfig flag was deprecated and we used it in the quick connect instructions. This removes mention of it and re-adds that users with multiple orgs/projects need to select a default to continue with setup.
This reverts back to the approved content replaced in [this PR](https://github.com/mongodb/docs-atlas-cli/pull/8/files), so the content has already been reviewed.

(DOCSP-22658) Removes --skipConfig option from connection instructions

---

.vscode/settings.json
snooty.toml
source/atlas-cli-getting-started.txt
source/atlas-cli-quickstart.txt
source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt

[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6284ebad55f596c31df19efd)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-22576)
[Staging 1](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22576-2/atlas-cli-getting-started/): Get Started with Atlas tutorial (within Atlas CLI docs. A different PR will edit Atlas docs)
[Staging 2](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22576-2/atlas-cli-tutorials/): New top-level page for tutorials
[Staging 3](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22576-2/connect-atlas-cli/): Connect from the Atlas CLI (small change)
[Staging …

(DOCSP-22576) Adds atlas setup tutorial

---

source/install-atlas-cli.txt

[DOCSP-22872](https://jira.mongodb.org/browse/DOCSP-22872)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22872-v2/install-atlas-cli/#follow-these-steps-1)
[Clean build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=628e831a7cf5397525cd0da3) (except for expected autocomplete command errors)

(DOCSP-22872): Fix brew upgrade typo

---

source/compatibility.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-23105)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-23105/compatibility/)

DOCSP-23105: remove RHEL 6 from atlas cli compat table

---

snooty.toml
source/compatibility.txt
source/install-atlas-cli.txt

[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62fd0970b354ebcf05237a17)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-24624)
[Staging 1](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-24110/install-atlas-cli/) (yum/apt tabs)
[Staging 2](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-24110/compatibility/)

(DOCSP-24624) Adds RHEL 9/Ubuntu 22.04 support, updates yum/apt to 6.0

---

source/install-atlas-cli.txt

- [DOCSP-24941](https://jira.mongodb.org/browse/DOCSP-24941)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-24941/install-atlas-cli/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=632209e89ef0f101154e08b7) (has errors unrelated to changes in this PR)

DOCSP-24941 Add support for Chocholatey to the installation options

---

source/compatibility.txt

[Jira](https://jira.mongodb.org/browse/DOCSP-25343)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=632a271e9ef0f10115741c46)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-25383/compatibility/)

(DOCSP-25383): Add Debian 11 and remove Debian 9 compatibility - Atlas CLI

---

source/atlas-cli-save-connection-settings.txt

- [DOCSP-25235](https://jira.mongodb.org/browse/DOCSP-25235)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=632b6aa49ef0f10115a340b8)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-25235/atlas-cli-save-connection-settings/) - see changes under Linux tab

DOCSP-25235 Add section on how to specifying a config file path

---

source/index.txt
source/install-atlas-cli.txt

[DOCSP-25907](https://jira.mongodb.org/browse/DOCSP-25907)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-25907/install-atlas-cli/) -- please find Debian tabs in the install and review those sections on this page.
Questions to reviewers:
When making updates, I noticed that the path to Debian ant is as follows:
`http://repo.mongodb.com/apt/debian/dists/bullseye/mongodb-enterprise/6.0/`
However, the paths in the docs are written without the /dists directory, and with /debian bullseye notation. I changed that but want to verify that this change is correct. It might be that there is some redirect in place that I am not observing.
If, however, this change is accurate, then this would apply to ubuntu paths as well. Please confirm or deny my …

(DOCSP-25907) Fix the Debian tabs

---

source/index.txt
source/install-atlas-cli.txt

Backport of #72 
Staging
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=635194a77f102f5cea399169) is clean.

Backport of DOCSP-25907 to Atlas CLI v1.2: Debian tabs and paths for Debian 10 and 11

---

source/cluster-config-file.txt
source/includes/geosharded-cluster-config-file.json

I tested the example config in Cloud Dev and it created a geosharded cluster with no issues.
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b457a9dc742b91f27324cc) (includes [known errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1646141185642329))
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-26171/cluster-config-file/#example-geosharded-cluster-configuration-file)

(DOCSP-26171) Adds example for geosharded cluster.

---

source/connect-atlas-cli.txt

[DOCSP-26322](https://jira.mongodb.org/browse/DOCSP-26322)
@jiayong0 and @tsck, could you please review?
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-26322/connect-atlas-cli/#connect-with-minimum-required-settings) (choose the "non-programmatic" tab)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63f4ebd105dd3cc814caf887)
@sarahsimpers, this must be merged and published only after this feature branch for Atlas gets merged and published ([ip-access-list-full](https://github.com/10gen/cloud-docs/tree/ip-access-list-full)).

(DOCSP-26322) Added an IP access list restriction

---

source/atlas-cli-create-cluster-from-config-file.txt
source/atlas-cli-tutorials.txt

- [JIRA](https://jira.mongodb.org/browse/DOCSP-29511)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-29511/atlas-cli-create-cluster-from-config-file/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644a95ee7efd2382b301f971)

DOCSP-29511 backport tutorial on using an existing cluster def to create a new cluster 

---

source/atlas-cli-create-cluster-from-config-file.txt
source/atlas-cli-tutorials.txt

- [JIRA](https://jira.mongodb.org/browse/DOCSP-29513)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/v1.6/atlas-cli-create-cluster-from-config-file/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644a998f7efd2382b302f768)

DOCSP-29513 backport tutorial on using an existing cluster def to create a new cluster

---

source/atlas-cli-create-cluster-from-config-file.txt
source/atlas-cli-tutorials.txt

- [JIRA](https://jira.mongodb.org/browse/DOCSP-29514)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-29514/atlas-cli-create-cluster-from-config-file/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644a9bb17efd2382b303a1d9)

DOCSP-29514 backport tutorial on using an existing cluster def to create a new cluster

---

snooty.toml
source/reference/json.txt
source/reference/json/cluster-config-file.txt

Adds info to JSON page about using the Open API spec to create JSON configuration files.
[Jira](https://jira.mongodb.org/browse/DOCSP-29111)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-29111/reference/json/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644c32b27efd2382b35f5c1f)

(DOCSP-29111): Add info on how to use the Open API spec to create JSON config files

---

source/includes/create-atlas-search-index-config-file.json
source/reference/json.txt
source/reference/json/search-index-config-file.txt

I tested this process with a file and confirmed that it successfully creates the index.
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-27483)
[Staging 1: top-level page for config files](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-27483/reference/json/)
[Staging 2: search index config file page](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-27483/reference/json/search-index-config-file/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64837b4467a273b816e4edbc) All build errors are unrelated

(DOCSP-27483) Adds guidance to create Atlas search index from a file

---

source/troubleshooting.txt

@andreaangiolillo and @jwilliams-mongo, I added the specific steps or accessing the API key access list to the following troubleshooting page.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-29595/troubleshooting/#403--request--forbidden---ip-address--ip-address--is-not-allowed-to-access-this-resource.)
[JIRA](https://jira.mongodb.org/browse/DOCSP-29595)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648c797a259a8493e5f5b12e)

(DOCSP-29595): Pulled in specific steps for API key access lists.

---

source/atlas-cli-changelog.txt

[JIRA](https://jira.mongodb.org/browse/DOCSP-31349)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b157f68d53f9c4af0c5647)
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31349/atlas-cli-changelog/#atlas-cli-1.9.0)

(DOCSP-31349) Adds deprecated Atlas CLI commands to v1.9 changelog.

---

source/atlas-cli-save-connection-settings.txt
source/connect-atlas-cli.txt
source/install-atlas-cli.txt
source/migrate-to-atlas-cli.txt

Aside from adding the Docker image as a way to install the Atlas CLI, this corrects the style of procedures in this repo to normal style.
[Jira](https://jira.mongodb.org/browse/DOCSP-30771)
[Staging (Docker tab)](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-30771/install-atlas-cli/#install-the-atlas-cli)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64bfeaed87b3b36046d6e57c)

(DOCSP-30771) Adds Docker image as way to install Atlas CLI

---

source/atlas-cli-save-connection-settings.txt
source/connect-atlas-cli.txt
source/install-atlas-cli.txt
source/migrate-to-atlas-cli.txt

Backports https://github.com/mongodb/docs-atlas-cli/pull/183 to stable (v1.10)

(DOCSP-30771) Adds Docker image as way to install Atlas CLI (#183)

---

source/troubleshooting.txt

Accidentally closed https://github.com/mongodb/docs-atlas-cli/pull/196 after some git mishaps - creating and merging this separate PR
[Jira](https://jira.mongodb.org/browse/DOCSP-32541)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e504f657e37806c54ebbd9)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-32541/troubleshooting/)

(DOCSP-32541): Fix broken Atlas links

---

source/includes/alert-configuration-config-file.json
source/reference/json.txt
source/reference/json/alert-config-file.txt
source/reference/json/search-index-config-file.txt

Question for reviewers: How descriptive do we want to be for the settings on this page? I erred on the conservative side to encourage users to use the Open API spec since the descriptions are much more detailed and extensive there. Let me know what you think.
`atlas alerts settings create` and `atlas alerts settings update` now support the `--file` option for a JSON configuration file input.
[Jira](https://jira.mongodb.org/browse/DOCSP-32865)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64fb629e24fcc731b47cc592)
- [JSON](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-32865/reference/json/)
- [Alert Configuration File](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-32865/referen …

(DOCSP-32865): Add details for config files for alert configurations

---

source/atlas-cli-deploy-local.txt

Reverts mongodb/docs-atlas-cli#215. [BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65259f71885de6b26b46be2c)

Revert "(DOCSP-33582): Removed rst syntax from code example."

---

source/atlas-cli-deploy-local.txt
source/atlas-cli-local-cloud.txt
source/index.txt

@boooczek and @lmkerbey-mdb, I updated to the landing page to include tabs for creating deployments and Atlas Search indexes. When I break the Atlas Search sections out of the local deployment tutorial, the link will go to the new page.
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-33498/#manage-atlas-from-the-command-line)
[JIRA](https://jira.mongodb.org/browse/DOCSP-33498)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65297eb1673b813c8f47a704)

(DOCSP-33498): Added deploy and search to landing page.

---

source/compatibility.txt
source/install-atlas-cli.txt

- https://jira.mongodb.org/browse/DOCSP-34513
- Stage:
- [Install](https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-34513/install-atlas-cli/)
- [Compatibility](https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-34513/compatibility/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656e42e47a5cb5fef5cd27ba)

DOCSP-34513 Add support for Debian 12

---

snooty.toml
source/atlas-cli-deploy-docker.txt

- [JIRA](https://jira.mongodb.org/browse/DOCSP-36053)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-36053/atlas-cli-deploy-docker/#create-a-local-atlas-deployment-with-docker-compose)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b9530e6b2f17c95af5acc4)

DOCSP-36053 Add a warning to docker compose mode on experimental status

---

source/atlas-cli-deploy-fts.txt
source/atlas-cli-deploy-local.txt
source/atlas-cli-local-cloud.txt

I updated the local tutorial and search tutorial for recent changes to the Atlas CLI and the upcoming vector search index change.
[Local Tutorial](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-34098/atlas-cli-deploy-local/#manage-a-local-atlas-deployment)
[Search Tutorial](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-34098/atlas-cli-deploy-fts/#use-atlas-vector-search-with-a-atlas-deployment)
https://jira.mongodb.org/browse/DOCSP-34098
https://jira.mongodb.org/browse/DOCSP-34247
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c526fe6b2f17c95a3edfe8)

(DOCSP-34098)(DOCSP-34247): Updated local tutorial and search tutorial.

---

source/atlas-cli-env-variables.txt
source/atlas-cli-save-connection-settings.txt

Documents HTTP Proxy support as we did for Mongo CLI in https://github.com/10gen/docs-mongocli/pull/665/
Question for @gssbzn, do we want to add examples for the ``NO_PROXY`` environmental variable as well?
- [DOCSP-37173](https://jira.mongodb.org/browse/DOCSP-37173)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de2ad37111165982ce7fea)
Staging:
- [Environmental Variables](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-37173/atlas-cli-env-variables/)
- [Save Connection Settings](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-37173/atlas-cli-save-connection-settings/)

(DOCSP-37173): Add documentation around HTTP Proxy support

---

source/reference/json/cloud-backup-schedule-config-file.txt

This new template for configuration file docs will ensure:
- Docs stay accurate as the OpenAPI spec changes
- Customers know how to use the OpenAPI docs to get this info
- Writers can easily copy/paste the template for new commands
[DOCSP](https://jira.mongodb.org/browse/DOCSP-37332)
[STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-37332-2/reference/json/cloud-backup-schedule-config-file/)
[LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e39d8211db7b0427ea4abe)

(DOCSP-37332) Changes configuration file template

---

source/includes/fact-deploy-tutorial-prereqs.rst

@blva and @sarahsimpers, I tried to clarify that the examples apply to MacOS and added extra links to the instructions for other operating systems.
- [DOCSP-37881](https://jira.mongodb.org/browse/DOCSP-37881)
- [STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-37881/atlas-cli-deploy-local/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66031e466fc5f048502a494c)

(DOCSP-37881): Clarified where to find the RHEL instructions for prereqs

---

source/atlas-cli-deploy-docker.txt

I added the missing Docker Compose line to the following page.
- [DOCSP-38423](https://jira.mongodb.org/browse/DOCSP-38423)
- [STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-38423/atlas-cli-deploy-docker/#update-your-docker-compose.yaml-file.)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6615360b3a5920a2917be3f7)

(DOCSP-38423): Added missing Docker compose line.

---

source/includes/steps-config-file-template-action-2.rst
source/includes/steps-config-file-template-action-3.rst
source/reference/json/alert-config-file.txt
source/reference/json/cluster-config-file.txt
source/reference/json/data-federation-config-file.txt
source/reference/json/file-options-online-archive.txt
source/reference/json/rolling-index-config-file.txt
source/reference/json/search-index-config-file.txt
source/reference/json/search-nodes-config-file.txt

This PR updates all remaining manually-documented config file pages to the template that was agreed-upon in #278. It also adds a second and third template to handle config file pages that should document more than one command (ones that support create + update, or clusters that support create, update, or upgrade)
Use of this template already has tech review approval from #278 
- [DOCSP-37380](https://jira.mongodb.org/browse/DOCSP-37380)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662154263a5920a2916cd567)
STAGING:
- [ADF config file](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-37380/reference/json/data-federation-config-file/)
- [Search nodes config file](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DO …

(DOCSP-37380) Updates all remaining config file pages to template

---

snooty.toml
source/atlas-cli-deploy-docker.txt

I updated the following page for the unified Docker image updates.
- [DOCSP-39082](https://jira.mongodb.org/browse/DOCSP-39082)
- [STAGING](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66420c1ccfd4ff22fd18afe5)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66420a3ecfd4ff22fd1846a4)

(DOCSP-39082): Updates local deploy with unified docker image.

---

source/compatibility.txt
source/install-atlas-cli.txt

@blva Can we confirm that these are the correct commands?
- [DOCSP-39429](https://jira.mongodb.org/browse/DOCSP-39429)
- Staging:
- [Install](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-39429/install-atlas-cli/)
- [Compatibility](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-39429/compatibility/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663d09e4b67dbf804a760575)

(DOCSP-39429): Add support for Amazon Linux 2023

---

snooty.toml

@melissamahoney-mongodb, I'm moving v1.5 to the Legacy site.
[DOCSP-40965](https://jira.mongodb.org/browse/DOCSP-40965)
[STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-40965/)
[LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667d7199ebce19f31496ff73)

(DOCSP-40965): Moving v1.5 to the Legacy site.

---

source/atlas-cli-deploy-docker.txt

Fix env var flag in example.
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123/atlas-cli-deploy-docker/#run-the-docker-image.)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c826debce19f31465d6f6)

DOCSP-40123 -- fix env var flag in example

---

source/reference.txt

Add SEO content to reference.txt
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-38355)
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-38355/reference/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668437e9fe162e50061fc245)

DOCSP-38355 -- add SEO content to reference.txt

---

source/atlas-cli-changelog.txt
source/atlas-cli-ephemeral-cluster.txt

The atlas quickstart command was removed from the CLI, so references to it cause build errors. This PR removes them.
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-41222)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-41222/atlas-cli-ephemeral-cluster/#std-label-atlas-cli-ephemeral-cluster)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668d90a6fb8bd13b84835305)
Tested and confirmed that the atlas setup command works as documented here in place of quickstart

(DOCSP-41222) Resolves quickstart build warnings

---

source/includes/fact-deploy-tutorial-prereqs.rst
source/troubleshooting.txt

Update local dev prereqs and troubleshooting from Podman to Docker.
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-41112)
- STAGING 
- https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-41112/atlas-cli-deploy-local/#complete-the-prerequisites
- https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-41112/troubleshooting/
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668c6078fb8bd13b843b83c2)

DOCSP-41112 -- Update local dev prereqs from Podman to Docker

---

snooty.toml
source/atlas-cli-changelog.txt
source/atlas-cli-ephemeral-cluster.txt

[DOCSP](https://jira.mongodb.org/browse/DOCSP-42635), plus backports https://github.com/mongodb/docs-atlas-cli/pull/447
See Netlify links for staging and build

(DOCSP-42635) Archives version 1.9 and backports build fixes

---

snooty.toml
source/atlas-cli-changelog.txt
source/atlas-cli-ephemeral-cluster.txt

[DOCSP](https://jira.mongodb.org/browse/DOCSP-42635), plus backports https://github.com/mongodb/docs-atlas-cli/pull/447
See Netlify links for staging and build

(DOCSP-42635) Archives version 1.10 and backports build fixes

---

source/install-atlas-cli.txt

@sarahsimpers and @gssbzn, I updated the steps to remove the deprecated `apt-key`.
- [DOCSP-41388](https://jira.mongodb.org/browse/DOCSP-41388)
- [STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-41388/install-atlas-cli/#complete-the-prerequisites-1)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c5eaa340f3e3c873e186b1)

(DOCSP-41388): Updated install steps to remove deprecated apt-key.

---

snooty.toml

This will backport the following commits from `master` to `v1.11`:

add banner to local deployment pages-v1.11-backport (642)

---

snooty.toml

This will backport the following commits from `master` to `v1.12`:

add banner to local deployment pages-v1.12-backport (642)

---

snooty.toml

This will backport the following commits from `master` to `v1.13`:

add banner to local deployment pages-v1.13-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.14-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.15-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.16-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.17-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.18-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.19-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.20-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.21-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.22-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.23-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.24-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.25-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.26-backport (642)

---

snooty.toml

add banner to local deployment pages-v1.27-backport (642)

---

source/command/atlas-performanceAdvisor-slowQueryLogs-list.txt

Updated the description of the nLog parameter to state the maximum value. (The description I choose is based on how I saw other places in the docs here talk about maximum values.
Note: Will backport this all the way to v1.21 after this PR is merged.
- [DOCSP-43449](https://jira.mongodb.org/browse/DOCSP-43449)
- [STAGING](https://deploy-preview-663--docs-atlas-cli.netlify.app/command/atlas-performanceAdvisor-slowQueryLogs-list/#options)

DOCSP-43449 updated text for nLogs param

---

source/atlas-cli-deploy-docker.txt

Add Automation example for local Atlas instance in Docker.
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-43190)
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-43190/atlas-cli-deploy-docker/#run-the-docker-image.) Under the tab "Automate Connection"
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66e339731b6f794a2e79a6f9)

DOCSP-43190 -- Add Automation example for local Atlas instance in Docker

---

source/atlas-cli-deploy-docker.txt

Automated deployment example in Docker -- backport to v1.28
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-43190)

DOCSP-43190 -- Automated deployment example in Docker -- backport to v1.28

---

source/atlas-cli-deploy-docker.txt

DOCSP-43190 -- Automated deployment example in Docker -- backport to v1.27
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-43190)

DOCSP-43190 -- Automated deployment example in Docker -- backport to v1.27

---

source/atlas-cli-deploy-docker.txt

DOCSP-43190 -- Automated deployment example in Docker -- backport to v1.26
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-43190)

DOCSP-43190 -- Automated deployment example in Docker -- backport to v1.26

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.29-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.28-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.27-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.26-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.25-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.24-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.23-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.22-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.20-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.19-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.16-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.15-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.14-backport (677)

---

source/atlas-cli-env-variables.txt

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.17-backport (677)

---

source/atlas-cli-env-variables.txt

This will backport the following commits from `master` to `v1.11`:

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.11-backport (677)

---

source/atlas-cli-env-variables.txt

This will backport the following commits from `master` to `v1.13`:

(DOCSP-42975) [Atlas CLI] Atlas CLI nested components-v1.13-backport (677)

---

source/atlas-cli-changelog.txt
source/troubleshooting.txt

Updated the troubleshooting page to contain a podman error, and updated the v1.26 rn with 2 additional bullets.
Note: I'll backport this to v1.26 after this PR is merged.
- [DOCSP-42444](https://jira.mongodb.org/browse/DOCSP-42444)
- STAGING
- [Troubleshooting](https://deploy-preview-708--docs-atlas-cli.netlify.app/troubleshooting/#podman-not-found)
- [v1.26 release notes](https://deploy-preview-708--docs-atlas-cli.netlify.app/atlas-cli-changelog/#atlas-cli-1.26.0)

DOCSP-42444 updated troubleshooting page with podman error

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.27-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.26-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.24-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.22-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.21-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.20-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.19-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.18-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.17-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.16-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.15-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

This will backport the following commits from `master` to `v1.13`:

DOCSP-44126-ToC-Refactor-v1.13-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

This will backport the following commits from `master` to `v1.12`:

DOCSP-44126-ToC-Refactor-v1.12-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

This will backport the following commits from `master` to `v1.11`:

DOCSP-44126-ToC-Refactor-v1.11-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.29-backport (709)

---

source/atlas-cli-tutorials.txt
source/connect-atlas-cli.txt
source/index.txt
source/install-atlas-cli.txt

DOCSP-44126-ToC-Refactor-v1.28-backport (709)

---

snooty.toml

Adds the EOL banner to v1.11 (Per [these EOL instructions](https://wiki.corp.mongodb.com/display/DE/How+To%3A+Sunset+an+EOL+Version+of+Documentation))
- [DOCSP-43971](https://jira.mongodb.org/browse/DOCSP-43971)
- [STAGING](https://deploy-preview-736--docs-atlas-cli.netlify.app)

DOCSP-42971-v1.11-EOL

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.27-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.26-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.25-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.24-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.23-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.22-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.21-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.20-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.19-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.18-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.17-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.16-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.15-backport (760)

---

source/atlas-cli-deploy-docker.txt

(DOCSP-45098) Updates localdev Docker compose example.-v1.14-backport (760)

---

source/atlas-cli-deploy-local.txt

@fmenezes, I've drafted all the updated for the Local Deployment page. Can you provide more information about the `--initdb` option? Where do the `.js` and `.sh` files come from?
- [DOCSP-45676](https://jira.mongodb.org/browse/45676)
- [DOCSP-45679](https://jira.mongodb.org/browse/45679)
- [DOCSP-45680](https://jira.mongodb.org/browse/45680)
- [STAGING](https://deploy-preview-784--docs-atlas-cli.netlify.app/atlas-cli-deploy-local/#move-a-local-atlas-deployment-to-a-cloud-atlas-deployment)

(DOCSP-45676), (DOCSP-45679), (DOCSP-45680): Updated Local Deployment page.

---

config/redirects

@jwilliams-mongo, I'm trying to set up a redirect to the [Page Unavailable in Version](https://www.mongodb.com/docs/unavailable-version/) page so that I have an example for the Lunch & Learn tomorrow.
- [DOCSP-45896](https://jira.mongodb.org/browse/DOCSP-45896)

(DOCSP-45896): Adds redirect for page unavailable in version example.

---

source/atlas-cli-deploy-docker.txt

- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-45301)

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.32-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.31-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.30-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.29-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.24-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.23-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.21-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.20-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.18-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.17-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.15-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.14-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.19-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.16-backport (783)

---

source/atlas-cli-deploy-docker.txt

DOCSP-45301 -- Add checklist and examples for converting from official image to local dev image-v1.25-backport (783)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.35-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.34-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.33-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.32-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.31-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.30-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.29-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.28-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.27-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-46401) Adds install workaround for m4 chips.-v1.26-backport (809)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.24`:

Backports DOCSP-46401 to v1.25-v1.24-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.23`:

Backports DOCSP-46401 to v1.25-v1.23-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.22`:

Backports DOCSP-46401 to v1.25-v1.22-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.21`:

Backports DOCSP-46401 to v1.25-v1.21-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.20`:

Backports DOCSP-46401 to v1.25-v1.20-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.19`:

Backports DOCSP-46401 to v1.25-v1.19-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.18`:

Backports DOCSP-46401 to v1.25-v1.18-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.16`:

Backports DOCSP-46401 to v1.25-v1.16-backport (821)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.14`:

Backports DOCSP-46401 to v1.25-v1.14-backport (821)

---

snooty.toml
source/command/atlas-api.txt
source/command/atlas.txt

- [DOCSP-46656](https://jira.mongodb.org/browse/DOCSP-46656)
- [STAGING](https://deploy-preview-838--docs-atlas-cli.netlify.app/command/atlas-api/)

(DOCSP-46656) Adds handwritten command for atlas api.

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.35-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.34-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.33-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.32-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.31-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.30-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.29-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.28-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.27-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.26-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.25-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.24-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.23-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.22-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.21-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.20-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.19-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.18-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.17-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.15-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.16-backport (844)

---

source/includes/steps-run-as-daemon.rst
source/includes/steps-run-interactive-mode.rst

DOCSP-46527 -- Add GitHub access requirement note-v1.14-backport (844)

---

source/atlas-cli-changelog.txt

- [(DOCSP-47205) Fixes build errors. (#872)](https://github.com/mongodb/docs-atlas-cli/pull/872)

(DOCSP-47205) Fixes build errors.-v1.38-backport (872)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.38-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `master` to `v1.36`:

(DOCSP-47165) Removes workaround per fix.-v1.36-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.35-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.34-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.33-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.32-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.31-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.29-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.28-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

(DOCSP-47165) Removes workaround per fix.-v1.27-backport (875)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.24`:

Backports DOCSP-47165 to v1.25-v1.24-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.23`:

Backports DOCSP-47165 to v1.25-v1.23-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.22`:

Backports DOCSP-47165 to v1.25-v1.22-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.21`:

Backports DOCSP-47165 to v1.25-v1.21-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.20`:

Backports DOCSP-47165 to v1.25-v1.20-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.19`:

Backports DOCSP-47165 to v1.25-v1.19-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.18`:

Backports DOCSP-47165 to v1.25-v1.18-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.17`:

Backports DOCSP-47165 to v1.25-v1.17-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.16`:

Backports DOCSP-47165 to v1.25-v1.16-backport (899)

---

source/atlas-cli-deploy-docker.txt
source/atlas-cli-deploy-local.txt
source/includes/fact-installation-workaround-m4chips.rst

This will backport the following commits from `v1.25` to `v1.15`:

Backports DOCSP-47165 to v1.25-v1.15-backport (899)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.38-backport (885)

---

source/troubleshooting.txt

This will backport the following commits from `master` to `v1.37`:

Docsp 46527 -- Add Troubleshooting entry-v1.37-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.35-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.34-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.33-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.23-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.21-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.19-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.17-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.15-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.20-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.18-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.14-backport (885)

---

source/troubleshooting.txt

This will backport the following commits from `master` to `v1.13`:

Docsp 46527 -- Add Troubleshooting entry-v1.13-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.32-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.16-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.31-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.30-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.29-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.28-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.27-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.26-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.25-backport (885)

---

source/troubleshooting.txt

Docsp 46527 -- Add Troubleshooting entry-v1.24-backport (885)

---

source/troubleshooting.txt

This will backport the following commits from `master` to `v1.12`:

Docsp 46527 -- Add Troubleshooting entry-v1.12-backport (885)

---

source/command/atlas-kubernetes-dry-run.txt
source/command/atlas-kubernetes-operator-install.txt
source/command/atlas-kubernetes-operator.txt
source/command/atlas-kubernetes.txt

- [DOCSP-48106](https://jira.mongodb.org/browse/DOCSP-48106)
- [STAGING](https://deploy-preview-948--docs-atlas-cli.netlify.app/command/atlas-kubernetes-dry-run/)

DOCSP-48106 -- add ako dry run commands

---

source/atlas-cli-changelog.txt

This will backport the following commits from `master` to `v1.41`:
- [DOCSP-48588: atlas cli 1.41.1 release notes (#966)](https://github.com/mongodb/docs-atlas-cli/pull/966)

DOCSP-48588: atlas cli 1.41.1 release notes-v1.41-backport (966)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.21-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

This will backport the following commits from `master` to `v1.41`:

add sunset version prompt-v1.41-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

This will backport the following commits from `master` to `v1.40`:

add sunset version prompt-v1.40-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

This will backport the following commits from `master` to `v1.39`:

add sunset version prompt-v1.39-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.38-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

This will backport the following commits from `master` to `v1.37`:

add sunset version prompt-v1.37-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

This will backport the following commits from `master` to `v1.36`:

add sunset version prompt-v1.36-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.35-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.34-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.33-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.32-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.31-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.30-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.29-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.27-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.26-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.25-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.24-backport (994)

---

.github/prompts/eol-branch.prompt.md
.gitignore

add sunset version prompt-v1.23-backport (994)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.39`:

prompt fix-v1.39-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.38-backport (1046)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.37`:

prompt fix-v1.37-backport (1046)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.36`:

prompt fix-v1.36-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.35-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.34-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.33-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.32-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.31-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.30-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.29-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.28-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.27-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.26-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.25-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.24-backport (1046)

---

.github/prompts/eol-branch.prompt.md

prompt fix-v1.23-backport (1046)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.41`:

final fix to prompt-v1.41-backport (1066)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.40`:

final fix to prompt-v1.40-backport (1066)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.39`:

final fix to prompt-v1.39-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.38-backport (1066)

---

.github/prompts/eol-branch.prompt.md

This will backport the following commits from `master` to `v1.37`:

final fix to prompt-v1.37-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.35-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.34-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.33-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.32-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.31-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.30-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.29-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.27-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.26-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.25-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.24-backport (1066)

---

.github/prompts/eol-branch.prompt.md

final fix to prompt-v1.23-backport (1066)

---

snooty.toml

This will backport the following commits from `master` to `v1.39`:
- [DOCSP-50382 Update all preview callouts to link to new preview info page (#1115)](https://github.com/mongodb/docs-atlas-cli/pull/1115)

DOCSP-50382 Update all preview callouts to link to new preview info page-v1.39-backport (1115)

---

snooty.toml

This will backport the following commits from `master` to `v1.40`:
- [DOCSP-50382 Update all preview callouts to link to new preview info page (#1115)](https://github.com/mongodb/docs-atlas-cli/pull/1115)

DOCSP-50382 Update all preview callouts to link to new preview info page-v1.40-backport (1115)
