mongodb/docs-atlas-cli

source/connect-atlas-cli.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6245ad152e8f69777c555b9d)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-21720)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-21720/connect-atlas-cli/#follow-these-steps)
=> (DOCSP-21720) Adds --skipConfig option to Connect page

source/install-atlas-cli.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6246d21a2e8f69777c93e9a6)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-21752)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-21752/install-atlas-cli/)
=> (DOCSP-21752) Fixes incorrect yum and apt install commands

source/connect-atlas-cli.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6262e60a0fdfea9c37295940)
Backports #16
=> (DOCSP-22150) Removes line re: need to be on access list for auth login

config/redirects
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=627983ab0fdfea9c378107e2)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-22530)
=> (DOCSP-22530) Adds redirect file for Atlas CLI and first redirect for base

config/redirects
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=627987d90fdfea9c3781fdfc)
=> (DOCSP-22530) Fixes redirect

config/redirects
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=627a69d40fdfea9c37a387e8)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-22540)
=> (DOCSP-22540) Fixes redirect for base

.vscode/settings.json, snooty.toml, source/atlas-cli-env-variables.txt, source/configure-optional-settings.txt, source/index.txt, source/telemetry.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6287c22855f596c31d74e271)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-20716)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-20716/telemetry/)
=> (DOCSP-20716) Documents telemetry for Atlas CLI

source/atlas-cli-changelog.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6287fa1055f596c31d81acd0)
=> (DOCSP-22816) Fixes date on release notes

snooty.toml
- [JIRA](https://jira.mongodb.org/browse/DOCSP-22541)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22541/command/atlas-dataLakes/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6282a7d455f596c31d91ea45) (errors unrelated to this PR)
=> DOCSP-22541 Clarification Note on CLI for MDBW

source/telemetry.txt
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6299f85d7cf53975259f7864)
[Jira Ticket Link](https://jira.mongodb.org/browse/DOCSP-22831)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-22831/telemetry/#learn-what-the-atlas-cli-tracks)
=> (DOCSP-22831) Adds back line stating that telemetry tracks some arguments

source/telemetry.txt
Backports #39 
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62a1d7b27cf5397525e57151)
=> (DOCSP-22831) Adds back line stating that telemetry tracks some arguments (#39)

source/install-atlas-cli.txt
Backports #49
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62ab21821e21bf77b18086e2)
=> Backports DOCSP-23230 to v1.1

source/includes/fact-more-than-500-orgs.rst, source/includes/steps-atlas-cli-add-profile-nonprogrammatic.rst
[Build Link](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62e82991230aeb802e082838)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-24159)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-24159/atlas-cli-save-connection-settings/#follow-these-steps) (Non-programmatic tab, step 5 for both sub-tabs)
=> (DOCSP-24159) Adds note that users with >500 orgs must filter results

source/install-atlas-cli.txt
- DOCSP-25328
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-25328/install-atlas-cli/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6324b8bc9ef0f10115b2ac91)
=> DOCSP-24941 Backport support for Chocholatey to the installation options

source/atlas-cli-quickstart.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=635aa4dc7f102f5cead3531d)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-26157)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-26157/atlas-cli-quickstart/)
=> (DOCSP-26157) Adds link to cluster create command and config file

source/atlas-cli-quickstart.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=636d148e7f102f5cea326541)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-26157)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-26157-stable/atlas-cli-quickstart/)
This content was copy reviewed in the PR against the master branch (#80)
=> (DOCSP-26157) Adds info about cluster config file to tutorial on creating clusters

source/atlas-cli-quickstart.txt
Backports #83 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=636d169a7f102f5cea32edb3)
=> Backports DOCSP-26157 to v1.0

source/atlas-cli-quickstart.txt
Backports #83 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=636d161c7f102f5cea32cb6a)
=> Backports DOCSP-26157 to v1.1

source/install-atlas-cli.txt
**NOTE** 
These file paths were previously edited in a [different merged commit](https://github.com/mongodb/docs-atlas-cli/pull/72). Based on testing with my own machine, it should work the same as stated in the [server docs](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/) (as documented with these new changes), however it seems like the behavior was different for the docs writers who tested it on their own machines. 
Confirmed with @gssbzn for the correct file paths. 
[JIRA](https://jira.mongodb.org/browse/DOCSP-27054)
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-27054-edit-atlascli-ubuntu-install/install-atlas-cli/#create-a-list-file-for-your-edition-of-mongodb.) - Please check Community and Enterprise for all …
=> DOCSP-27054 Edit AtlasCLI Installation for Apt

source/cluster-config-file.txt, source/includes/geosharded-cluster-config-file.json
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b485a2dc742b91f27ddae6) (includes [known errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1646141185642329))
Backports #90
=> Backports DOCSP-26171 to v1.4.

source/cluster-config-file.txt, source/includes/geosharded-cluster-config-file.json
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b48805dc742b91f27e625f) (includes [known errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1646141185642329))
Backports #90
=> Backports DOCSP-26171 to v1.3.

source/cluster-config-file.txt, source/includes/geosharded-cluster-config-file.json
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b48ac0dc742b91f27f0736) (includes [known errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1646141185642329)) 
Backports #90
=> Backports DOCSP-26171 to v1.1.

source/cluster-config-file.txt, source/includes/geosharded-cluster-config-file.json
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63b48f4edc742b91f2802daa)(includes [known errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1646141185642329))
Backports #90
=> Backports DOCSP-26171 to v1.0.

source/atlas-cli-save-connection-settings.txt, source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060c80054271fb0aa1717d)
[Jira Ticket 1](https://jira.mongodb.org/browse/DOCSP-28387)
[Jira Ticket 2](https://jira.mongodb.org/browse/DOCSP-28289)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-28387/troubleshooting/)
=> (DOCSP-28387)(DOCSP-28289) Adds troubleshooting page

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060e7d054271fb0aa2021f)
Backports #105
=> Backports DOCSP-28387 to v1.4

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060e61054271fb0aa1faed)
Backports #105
=> Backports DOCSP-28387 to v1.5

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060eee054271fb0aa21bc4)
Backports #105
=> Backports DOCSP-28387 to v1.3

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060f25054271fb0aa227d8)
Backports #105
=> Backports DOCSP-28387 to v1.2

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64060f4f054271fb0aa23916)
Backports #105
=> Backports DOCSP-28387 to v1.1

source/index.txt, source/troubleshooting.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6406100c054271fb0aa267ac)
Backports #105
=> Backports DOCSP-28387 to v1.0

source/atlas-cli-save-connection-settings.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63f8ac5e05dd3cc8149037e0)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-28064)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-28064/atlas-cli-save-connection-settings/#follow-these-steps)
=> (DOCSP-28064) Changes incorrect include file for programmatic steps

source/atlas-cli-save-connection-settings.txt
Backports #104 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64107df6b070a416374f828f)
=> Backports DOCSP-28064 to v1.4

source/atlas-cli-save-connection-settings.txt
Backports #104 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64107e37b070a416374f9065)
=> Backports DOCSP-28064 to v1.3

source/atlas-cli-save-connection-settings.txt
Backports #104 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=641082ecb070a4163750cb4f)
=> Backports DOCSP-28064 to v1.1

source/configure-optional-settings.txt, source/custom-output-cli.txt
- https://jira.mongodb.org/browse/DOCSP-28576
- Build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=641085ceb070a4163751954f
=> DOCSP-28576: Backport DOCSP-25516

source/configure-optional-settings.txt, source/custom-output-cli.txt
DOCSP-25516 Add missing content on custom output (https://github.com/mongodb/docs-atlas-cli/pull/103)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6410d478b070a41637661382
=> DOCSP-28576: Backport DOCSP-25516 to 1.2

source/configure-optional-settings.txt, source/custom-output-cli.txt
DOCSP-25516 Add missing content on custom output (https://github.com/mongodb/docs-atlas-cli/pull/103)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6410d4a1b070a41637661d1a
=> DOCSP-28576: Backport DOCSP-25516 to 1.1

source/configure-optional-settings.txt, source/custom-output-cli.txt
DOCSP-25516 Add missing content on custom output (#103)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6410d50fb070a416376632c8
=> DOCSP-28576: Backport DOCSP-25516 to 1.0

config/redirects
https://jira.mongodb.org/browse/DOCSP-28477
adding redirects per https://docs.google.com/spreadsheets/d/1kUJrOms7VAafDW2vUFKKYzuEkuAIoHVAP-QNNW_Jiuo/edit#gid=0
=> DOCSP-28477: add redirects

config/redirects, source/reference/json/cluster-config-file.txt
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-29108)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-29108-2/reference/json/cluster-config-file/#required-cluster-settings)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6436b834b49106a498641154)
=> (DOCSP-29108) Adds redirect for cluster config file and changes a link

config/redirects, source/reference/json/cluster-config-file.txt
Backports #127
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6436bf7bb49106a49865ed44)
=> Backports DOCSP-29108 to v1.6

snooty.toml, source/reference/json.txt, source/reference/json/cluster-config-file.txt
Backports https://github.com/mongodb/docs-atlas-cli/pull/134 to v1.6
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64515dae7efd2382b347a93c)
=> (DOCSP-29627): Backport DOCSP-29111 to v1.6 

snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-29791)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=647652dc67a273b81685a310)
=> (DOCSP-29791):  Sunset Atlas CLI version 1.1

snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-29791)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6476525267a273b816857237)
=> (DOCSP-29791):  Sunset Atlas CLI version 1.0 

source/atlas-cli-changelog.txt
[JIRA](https://jira.mongodb.org/browse/CLOUDP-180327)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648364e067a273b816ddb3f6) (includes [expected errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1679333780930919?thread_ts=1679333691.066079&cid=CGX40QH7Z))
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-30272/atlas-cli-changelog/#atlas-cli-1.7.1)
=> (DOCSP-30272) Adds RNs for 1.7.1.

source/atlas-cli-changelog.txt
[JIRA](https://jira.mongodb.org/browse/CLOUDP-180327)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648376ec67a273b816e3b6e7) (includes [expected errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1679333780930919?thread_ts=1679333691.066079&cid=CGX40QH7Z))
Backports #150
=> Backports DOCSP-30272 to 1.7.

source/includes/create-atlas-search-index-config-file.json, source/reference/json.txt, source/reference/json/search-index-config-file.txt
Backports #146 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64837bbb67a273b816e50c15)
=> Backports DOCSP-27483 to v1.7

source/atlas-cli-changelog.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-30497)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64873beb67a273b81692b10f) (includes [expected errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1679333780930919?thread_ts=1679333691.066079&cid=CGX40QH7Z))
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-30497/atlas-cli-changelog/#atlas-cli-1.7.2)
=> (DOCSP-30497) Adds RN for cluster tagging flag.

source/atlas-cli-changelog.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-30497)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6489f26367a273b816347f8a)
Backports #153
=> Backports DOCSP-30497 to v1.7

source/troubleshooting.txt
* (DOCSP-29595): Pulled in specific steps for API key access lists.
* (DOCSP-29595): Test commit.
* (DOCSP-29595): Test commit.
* (DOCSP-29595): Test commit.
* (DOCSP-29595): Test commit
* (DOCSP-29595): Incorporated JW's feedback.
* (DOCSP-29595): Incorporated Andrea's feedback.
* (DOCSP-29595): Incorporated Andrea's feedback.
=> (DOCSP-29595): Pulled in specific steps for API key access lists. (#156)

source/reference/json/cluster-config-file.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-30302)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649474bd423952aeb96bd242) (includes [expected errors](https://mongodb.slack.com/archives/CGX40QH7Z/p1679333780930919?thread_ts=1679333691.066079&cid=CGX40QH7Z))
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-30302/reference/json/cluster-config-file/#optional-and-conditional-cluster-settings:~:text=tags,production%20in%20the%20environment%20%3A%20production%20tag.)
=> (DOCSP-30302) Adds new tag option.

source/atlas-cli-ephemeral-cluster.txt, source/atlas-cli-tutorials.txt
These changes were already approved in https://github.com/mongodb/docs-atlas-cli/pull/164 but were not merged properly. This PR merges the changes.
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b0efc423952aeb9e5a314)
=> (DOCSP-25302) Adds ephemeral clusters tutorial

source/atlas-cli-ephemeral-cluster.txt, source/atlas-cli-tutorials.txt
Backports #167 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b1343423952aeb9e7a248)
=> Backports DOCSP-25302 to v1.7

source/atlas-cli-ephemeral-cluster.txt, source/atlas-cli-tutorials.txt
Backports #167 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b13b4423952aeb9e7f06b)
=> Backports DOCSP-25302 to v1.6

source/atlas-cli-ephemeral-cluster.txt, source/atlas-cli-tutorials.txt
Backports #167 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b1471423952aeb9e82495)
=> Backports DOCSP-25302 to v1.5

source/atlas-cli-ephemeral-cluster.txt, source/atlas-cli-tutorials.txt
Backports #167
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b14b5423952aeb9e853cd)
=> Backports DOCSP-25302 to v1.4

source/atlas-cli-changelog.txt
Added a missing RN item.
[JIRA](https://jira.mongodb.org/browse/DOCSP-31032)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31032/atlas-cli-changelog/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649c811f423952aeb9616642)
=> DOCSP-31032 added missing rn item

source/compatibility.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-31172)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31172/compatibility/#mongodb-service-versions)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64a6c855423952aeb9b25437)
=> (DOCSP-31172) Adds MongoDB Server support info

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64a6d2f5423952aeb9b5424f)
Backports #174
=> Backports DOCSP-31172 to v1.8

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64a6d383423952aeb9b5a08f)
Backports #174
=> Backports DOCSP-31172 to v1.7

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64a6d3bf423952aeb9b5ae50)
Backports #174
=> Backports DOCSP-31172 to v1.6

source/atlas-cli-changelog.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-31349)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b15f208d53f9c4af0f4fd5)
Backports #181
=> Backports DOCSP-31349 to v1.9

snooty.toml, source/includes/data-federation-instance-config-file.json, source/reference/json.txt, source/reference/json/data-federation-config-file.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-31036)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b19c258d53f9c4af26c4c9)
STAGING:
- [JSON](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31036/reference/json/)
- [Atlas Data Federation Configuration File](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31036/reference/json/data-federation-config-file/)
=> (DOCSP-31036) Adds example data federation config file.

snooty.toml, source/includes/data-federation-instance-config-file.json, source/reference/json.txt, source/reference/json/data-federation-config-file.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-31036)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b5c55587b3b36046253109)
Backports #180
=> Backports DOCSP-31036 to v1.9.

source/atlas-cli-changelog.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-31499)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31499/atlas-cli-changelog/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ba884487b3b36046b6aa3c) (has errors)
=> DOCSP-31499 Release notes, source constant updates for v1.9.2

source/atlas-cli-changelog.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-31517)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-31517/atlas-cli-changelog/#atlas-cli-1.9.0)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ba8c3b87b3b36046b81b61)
=> DOCSP-31499 Release notes, source constant updates for v1.9.2 (#185)

source/atlas-cli-quickstart.txt
Backports #191 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64da2ebb67dbe91010864a29)
=> Backports DOCSP-31520 to v1.10

source/atlas-cli-docker.txt, source/atlas-cli-tutorials.txt, source/includes/steps-run-as-daemon.rst, source/includes/steps-run-interactive-mode.rst, source/install-atlas-cli.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-32090)
[Staging 1: New Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-32090/atlas-cli-docker/)
[Staging 2: Top-level tutorials page](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-32090/atlas-cli-tutorials/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e4adcf57e37806c533c55b)
=> (DOCSP-32090) Tutorial to run commands with Docker

source/atlas-cli-docker.txt, source/atlas-cli-tutorials.txt, source/includes/steps-run-as-daemon.rst, source/includes/steps-run-interactive-mode.rst, source/install-atlas-cli.txt
Backports #190 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e4c5ea57e37806c53acbeb)
=> Backports DOCSP-32090 to v1.10

facets.toml, source/facets.toml, source/reference/facets.toml
Hey @jwilliams-mongo!
I've tried out the programmatic tagging script from DOP, and I think it worked ok, but I would appreciate your review!  Since we don't have search filtering live on the site, merging this won't affect anything on the front end.  The count of pages with tags should go up, though.
Thanks!
Sarah
=> Add programmatic taxonomy tags for product & genre

source/compatibility.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-33104)
[Staging](https://preview-mongodbzachcarr.gatsbyjs.io/atlas-cli/DOCSP-33104/compatibility/)
[Build - errors](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650894de492df295cf81527a)
=> (DOCSP-33104) EOL Ubuntu 18.04

source/atlas-cli-changelog.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650dff2a492df295cff875ba)
=> (DOCSP-33221): Added release dates.

source/atlas-cli-changelog.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650e003b492df295cff8ed0e)
=> (DOCSP-33079): Added release dates.

source/atlas-cli-deploy-local.txt
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-33276/atlas-cli-deploy-local/#supported-os-for-local-atlas-deployments)
[JIRA](https://jira.mongodb.org/browse/DOCSP-33276)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6511cc48492df295cfa5fc32)
=> (DOCSP-33276): Removed Amazon Linux for Local Deploy.

source/atlas-cli-deploy-local.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6511cdbf492df295cfa6622b)
=> (DOCSP-33277): Backport DOCSP-33276 to v1.12. (#209)

source/install-atlas-cli.txt
Hi @jwilliams-mongo,
Just one top 250 page for the atlas-cli repo, with correct spacing and facet/name.  Please merge when you are able!
Thank you!
Sarah
=> DOCSP-27817 manual tags for the atlas cli top 250 pages

source/atlas-cli-deploy-local.txt
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-33582a/atlas-cli-deploy-local/#specify-a-deployment-name.)
[JIRA](https://jira.mongodb.org/browse/DOCSP-33582)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6525a2a2885de6b26b47f211)
=> (DOCSP-33582): Removed rst syntax from code example.

source/atlas-cli-deploy-local.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6525a475885de6b26b48ca4a)
=> (DOCSP-33583): Backport DOCSP-33582 to v1.12.

source/atlas-cli-deploy-local.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=652fd140673b813c8faa6c1a)
=> (DOCSP-33753): Backport DOCSP-33494 to v1.12. (#221)

source/atlas-cli-deploy-local.txt, source/atlas-cli-local-cloud.txt, source/index.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65492fe5bd8a7a9579578eba)
=> (DOCSP-34100): Backport DOCSP-33498 to v1.12. (#219)

source/atlas-cli-automate.txt, source/atlas-cli-local-cloud.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
I updated the Atlas TOC Labels.
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-34815/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-34815)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657355827a5cb5fef5333be4)
=> (DOCSP-34815): Updated the Atlas CLI TOC labels.

source/atlas-cli-automate.txt, source/atlas-cli-local-cloud.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65773c557a5cb5fef5002e44)
=> (DOCSP-34899): Backport DOCSP-34815 to v1.13. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65773ec47a5cb5fef5011edb)
=> (DOCSP-34898): Backort DOCSP-34815 to v1.11. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6577405f7a5cb5fef5021b1c)
=> (DOCSP-34900): Backport DOCSP-34815 to v1.10. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657741c57a5cb5fef502c75d)
=> (DOCSP-34901) Backport DOCSP-34815 v1.9. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657744f97a5cb5fef50445dd)
=> (DOPCSP-34903): Backport DOCSP-34815 to v1.8. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6577462a7a5cb5fef504c558)
=> (DOCSP-34905): Backport DOCSP-34815 to v1.7. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt, source/reference/json.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657747247a5cb5fef5051a59)
=> (DOCSP-34906): Backport DOCSP-34815 to v1.6. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657749037a5cb5fef505a2ad)
=> (DOCSP-34907): Backport DOCSP-34815 to v1.5. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65774b9c7a5cb5fef5068ef5)
=> (DOCSP-34909): Backport DOCSP-34815 to v1.3. (#234)

source/atlas-cli-automate.txt, source/atlas-cli-tutorials.txt, source/index.txt, source/reference.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65774ccb7a5cb5fef506f46b)
=> (DOCSP-34910): Backport DOCSP-34815 to v1.2. (#234)

source/includes/create-atlas-search-expanded-index-config-file.json, source/reference/json/search-index-config-file.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-34512)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-34512/reference/json/search-index-config-file/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657c8af97a5cb5fef58307e7)
=> DOCSP-34512 update steps for Atlas Search Index Configuration File

source/atlas-cli-deploy-docker.txt, source/atlas-cli-docker.txt, source/atlas-cli-local-cloud.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=658310227a5cb5fef503a9aa)
* (DOCSP-34859): Added local deploy in docker.
* (DOCSP-34859): Incorporated Sarah's feedback.
* (DOCSP-34859): Incorporated Jakub's feedback.
* (DOCSP-34859): Incorporated final comments.
=> (DOCSP-35163): Backport DOCSP-34859 to v1.14. (#247)

snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-35621)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a968428aeba96efb1d0189)
=> (DOCSP-35621): Archive Atlas CLI version 1.2

snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-35621)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a967e58aeba96efb1cc6e1)
=> (DOCSP-35621): Archive Atlas CLI version 1.3

snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-35621)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a967ff8aeba96efb1cce0f)
=> (DOCSP-35621): Archive Atlas CLI version 1.4

source/atlas-cli-deploy-local.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b7bbd894771f7657bcbbb3)
Backports #256
=> Backports DOCSP-35993 to v1.14

source/atlas-cli-deploy-local.txt
Backports #256 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b7bd0394771f7657bd291b)
=> Backports DOCSP-35993 to v1.12

source/includes/online-archive-create.json, source/includes/online-archive-update.json, source/reference/json.txt, source/reference/json/file-options-online-archive.txt
Add Online Archive Create and Update JSON config options page.
[JIRA](https://jira.mongodb.org/browse/DOCSP-34286)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a954358aeba96efb124737)
[STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-34286/reference/json/file-options-online-archive/)
=> DOCSP-34286 -- Add Online Archive Create and Update JSON config options page

source/atlas-cli-automate.txt, source/includes/online-archive-create.json, source/includes/online-archive-update.json, source/reference/json.txt, source/reference/json/file-options-online-archive.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b9738f6b2f17c95a0857e2)
=> Docsp 34286 Backport to v1.14 

.github/pull-request-template.md
[DOCSP-36965](https://jira.mongodb.org/browse/DOCSP-36965)
@sarahsimpers , could you please review? I am not sure we need all of these checks in the PR template -- lmk please which to remove, if any. Thank you!
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d02fc171111659827ef96c)
=> (DOCSP-36965) Add a PR template to this repo

source/atlas-cli-deploy-local.txt
Backports #269
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d8ddf17111165982acfee5)
=> Backports DOCSP-36970 to v1.14

source/atlas-cli-deploy-local.txt
Backports #269
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d8de717111165982ad2b6b)
=> Backports DOCSP-36970 to v1.15

source/atlas-cli-deploy-local.txt
Backports #269
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d8dead7111165982ad4626)
=> Backports DOCSP-36970 to v1.13

source/includes/create-search-node-config-file.json, source/reference/json.txt, source/reference/json/search-index-config-file.txt, source/reference/json/search-nodes-config-file.txt
- [DOCSP-36734](https://jira.mongodb.org/browse/DOCSP-36734)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&amp;jobId=65d8f4217111165982b71962)
Staging:
- [JSON landing page](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-36734/reference/json/)
- [Search Nodes Configuration File](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-36734/reference/json/search-nodes-config-file/)
=> (DOCSP-36734): Add JSON configuration page for Atlas Search Nodes

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e733a211db7b0427ab8d14)
=> Backports DOCSP-37332 to v1.15

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e733f711db7b0427abaa82)
=> Backports DOCSP-37332 to v1.14

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e7373111db7b0427acc861)
=> Backports DOCSP-37332 to v1.13

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e7377d11db7b0427acea54)
=> Backports DOCSP-37332 to v1.12

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e737c411db7b0427ad0816)
=> Backports DOCSP-37332 to v1.11

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e7380011db7b0427ad2abe)
=> Backports DOCSP-37332 to v1.10

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e738b911db7b0427ad71d1)
=> Backports DOCSP-37332 to v1.9

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e7390011db7b0427ad960a)
=> Backports DOCSP-37332 to v1.8

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e7399911db7b0427adc40e)
=> Backports DOCSP-37332 to v1.7

source/reference/json/cloud-backup-schedule-config-file.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e739dc11db7b0427adf50c)
=> Backports DOCSP-37332 to v1.6

source/includes/fact-deploy-tutorial-prereqs.rst
- https://jira.mongodb.org/browse/DOCSP-37455
- [STAGING](https://preview-mongodbjwilliamsmongo.gatsbyjs.io/atlas-cli/DOCSP-37455/atlas-cli-deploy-local/#complete-the-prerequisites)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ea3ba46fc5f048506a6d99)
=> DOCSP-37455: fix tools install command

source/atlas-cli-changelog.txt
- https://jira.mongodb.org/browse/DOCSP-37456
- [STAGING](https://preview-mongodbjwilliamsmongo.gatsbyjs.io/atlas-cli/DOCSP-37456/atlas-cli-changelog/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ea32c66fc5f04850671ab2)
=> DOCSP-37456: atlascli 1.16.0 release notes

config/redirects
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-37638)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f06f9a6fc5f04850bc29a5)
=> (DOCSP-37638) Adds symlinks for Atlas CLI docs

source/migrate-to-atlas-cli.txt
Backports #299 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f2328f6fc5f0485048a1aa)
=> Backports DOCSP-37597 to v1.16

source/atlas-cli-deploy-docker.txt
- [DOCSP-37438](https://jira.mongodb.org/browse/DOCSP-37438)
- [STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-37438/atlas-cli-deploy-docker/#persist-data-across-runs-with-docker-compose)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f987276fc5f04850e14f15)
=> (DOCSP-37438): Added details about persisting data.

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f98a5c6fc5f04850e205fe)
* (DOCSP-37438): Added details about persisting data.
* (DOCSP_37438): Incorporated Max's feedback.
* (DOCSP-37438): Incorporated Sarah's feedback.
* (DOCSP-37438): Incorporated final comments.
=> (DOCSP-37791): Backport DOCSP-37438 to v1.17. (#303)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f98bac6fc5f04850e26483)
* (DOCSP-37438): Added details about persisting data.
* (DOCSP_37438): Incorporated Max's feedback.
* (DOCSP-37438): Incorporated Sarah's feedback.
* (DOCSP-37438): Incorporated final comments.
=> (DOCSP-37792): Backport DOCSP-37438 to v1.16. (#303)

source/atlas-cli-deploy-docker.txt
* (DOCSP-37438): Added details about persisting data.
* (DOCSP_37438): Incorporated Max's feedback.
* (DOCSP-37438): Incorporated Sarah's feedback.
* (DOCSP-37438): Incorporated final comments.
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f98dbc6fc5f04850e30105)
=> (DOCSP-37793): Backport DOCSP-37438 to v1.15. (#303)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f98e8a6fc5f04850e33f15)
* (DOCSP-37438): Added details about persisting data.
* (DOCSP_37438): Incorporated Max's feedback.
* (DOCSP-37438): Incorporated Sarah's feedback.
* (DOCSP-37438): Incorporated final comments.
=> (DOCSP-37794): Backport DOCSP-37438 to v1.14. (#303)

source/troubleshooting.txt
- [DOCSP-37745](https://jira.mongodb.org/browse/DOCSP-37745)
- [STAGING](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-37745/troubleshooting/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f8c4e66fc5f04850bbbeae)
=> (DOCSP-37745): Typo fix on Troubleshoot Errors errors

source/troubleshooting.txt
=> Backport DOCSP-37734 to v1.17 (#305)

source/troubleshooting.txt
=> Backport DOCSP-37734 to v1.16 (#305)

source/troubleshooting.txt
=> Backport DOCSP-37734 to v1.15 (#305)

source/troubleshooting.txt
=> Backport DOCSP-37734 to v1.13 (#305)

source/troubleshooting.txt
=> Backport DOCSP-37734 to v1.12 (#305)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660172cf6fc5f04850b0926e)
=> (DOCSP-37992): Fixes typo in Docker Compose file (#316)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660174996fc5f04850b0fab4)
=> (DOCSP-37993): Fixes typo in Docker Compose file (#316)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6601753a6fc5f04850b12909)
=> (DOCSP-37994): Fixes typo in Docker Compose file (#316)

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/fix-errors/migrate-to-atlas-cli/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6602f6fa6fc5f0485015afae)
=> Fixes build errors related to submodule

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6602f7d36fc5f0485016110d)
=> Backports #322 to v1.16

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6602faf06fc5f0485017e162)
=>  Backports #322 to v1.15

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6602fb3b6fc5f0485017fd5e)
=> Backports #322 to v1.14

source/includes/fact-deploy-tutorial-prereqs.rst
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660324496fc5f048502c9912)
=> (DOCSP-38067): Backport DOCSP-37881 to v1.17. (#321)

source/includes/fact-deploy-tutorial-prereqs.rst
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660325216fc5f048502cf370)
=> (DOCSP-38068): Backport DOCSP-37881 to v1.16. (#321)

source/includes/fact-deploy-tutorial-prereqs.rst
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660325d96fc5f048502dc893)
=> (DOCSP-38069): Backport DOCSP-37881 to v1.15. (#321)

source/includes/fact-deploy-tutorial-prereqs.rst
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660326c56fc5f048502e3aab)
=> (DOCSP-38070): Backport DOCSP-37881 to v1.14. (#321)

source/includes/fact-deploy-tutorial-prereqs.rst
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6603281f6fc5f048502ece54)
=> (DOCSP-38072): Backport DOCSP-37881 to v1.12. (#321)

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040c946fc5f0485062d0f6)
=> Backports #322 to v1.13

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040cde6fc5f0485062ea44)
=> Backports #322 to v1.12

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040d2f6fc5f048506306d7)
=> Backports #322 to v1.11

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040d7f6fc5f04850632154)
=> Backports #322 to v1.10

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040e0f6fc5f04850634877)
=> Backports #322 to v1.9

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66040fd56fc5f0485063aeb7)
=> Backports #322 to v1.8

source/atlas-cli-changelog.txt, source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/install-atlas-cli.txt, source/migrate-to-atlas-cli.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660410276fc5f0485063c9ae)
=> Backports #322 to v1.7

source/atlas-cli-changelog.txt, source/install-atlas-cli.txt, source/verify-packages.txt
I have tested these processes, including the Windows process. The attached screenshot shows the Windows process output since I know this will be difficult for a copy reviewer to verify.
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-36718)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-36718-2/verify-packages/#std-label-verify-packages)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66044fa46fc5f048507b2a2a)
=> (DOCSP-36718) Confirm signatures on Atlas CLI packages

source/atlas-cli-changelog.txt, source/install-atlas-cli.txt, source/verify-packages.txt
Backports #304 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6605621f6fc5f04850bfac84)
=> Backports DOCSP-36718 to v1.17

source/atlas-cli-changelog.txt, source/install-atlas-cli.txt, source/verify-packages.txt
Backports #304 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6605626c6fc5f04850bfc7c8)
=> Backports DOCSP-36718 to v1.16

source/atlas-cli-changelog.txt, source/install-atlas-cli.txt, source/verify-packages.txt
Backports #304
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660562a76fc5f04850bfdf2e)
=> Backports DOCSP-36718 to v1.15

source/atlas-cli-changelog.txt, source/install-atlas-cli.txt, source/verify-packages.txt
Backports #304 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660562f06fc5f04850bffad2)
=> Backports DOCSP-36718 to v1.14

source/install-atlas-cli.txt
Hey @jwilliams-mongo!  There's just one page for the Atlas CLI in the top 250.  I took the first sentence; please edit if you think it should be different.
Thanks!
Sarah
staging: https://preview-mongodbsarahemlin.gatsbyjs.io/atlas-cli/DOCSP-33172/
build log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660c2ad13a5920a291433bc5
Jira ticket: https://jira.mongodb.org/browse/DOCSP-33172
=> DOCSP-33172 added meta description for top 250 pages in docs-atlas-cli

source/atlas-cli-changelog.txt
Added the v1.18 release notes.
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-38088)
- [STAGING](https://preview-mongodbkyuanmongodb.gatsbyjs.io/atlas-cli/DOCSP-38088/atlas-cli-changelog/#atlas-cli-1.18.0)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660c72b63a5920a29163addd)
=> DOCSP-38088 added the v1.18 release notes

source/atlas-cli-deploy-fts.txt, source/includes/fact-avs-mdb-version.rst, source/reference/json.txt, source/reference/json/rolling-index-config-file.txt, source/reference/json/search-index-config-file.txt
- [DOCSP-37703](https://jira.mongodb.org/browse/DOCSP-37703)
- STAGING
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-37703/reference/json/search-index-config-file/
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-37703/reference/json/rolling-index-config-file/
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660acd6f3a5920a291ebd48e) (contains errors not introduced by changes in this PR)
=> DOCSP-37703 Document how to create indexes with options in Atlas CLI

source/atlas-cli-deploy-docker.txt
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66153fb73a5920a2917df92f)
=> (DOCSP-38424): Backport DOCSP-38423 to v1.18. (#349)

source/atlas-cli-deploy-docker.txt
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6615405d3a5920a2917e4377)
=> (DOCSP-38425): Backport DOCSP-38423 to v1.17. (#349)

source/atlas-cli-deploy-docker.txt
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6615415b3a5920a2917e93ac)
=> (DOCSP-38427): Backport DOCSP-38423 to v1.15. (#349)

source/atlas-cli-deploy-docker.txt
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661541cc3a5920a2917ebcbc)
=> (DOCSP-38428): Backport DOCSP-38423 to v1.14. (#349)

source/includes/steps-config-file-template.rst, source/reference/json.txt, source/reference/json/project-config-file.txt, source/reference/json/rolling-index-config-file.txt
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-38401)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-38401/reference/json/project-config-file/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661fdb673a5920a29100b191)
=> (DOCSP-38401) Documents config file for projects update

source/includes/steps-config-file-template.rst, source/reference/json.txt, source/reference/json/project-config-file.txt, source/reference/json/rolling-index-config-file.txt
Backports #348 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661fdc033a5920a29100e33b)
=> Backports DOCSP-38401 to v1.20

source/includes/steps-config-file-template-action-2.rst, source/includes/steps-config-file-template-action-3.rst, source/reference/json/alert-config-file.txt, source/reference/json/cluster-config-file.txt, source/reference/json/data-federation-config-file.txt, source/reference/json/file-options-online-archive.txt, source/reference/json/rolling-index-config-file.txt, source/reference/json/search-index-config-file.txt, source/reference/json/search-nodes-config-file.txt
Backports #358 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66216916132d178bc187e86e)
=> Backports DOCSP-37380 to v1.20

source/compatibility.txt
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-38876)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-38876/compatibility/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66328377b67dbf804a036cfd)
=> (DOCSP-38876) Updates MacOS compatibility

source/compatibility.txt
Backports #361
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663287ecb67dbf804a057580)
=> Backports DOCSP-38876 to v1.21

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66328a0cb67dbf804a06d80f)
=> Backports DOCSP-38876 to v1.20

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66328a6eb67dbf804a07008f)
=> Backports DOCSP-38876 to v1.19

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66328ad2b67dbf804a0732aa)
=> Backports DOCSP-38876 to v1.18

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663294f2b67dbf804a0bcaef)
=> Backports DOCSP-38876 to v1.17

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66422415cfd4ff22fd1e8845)
=> (DOCSP-39464): Backport DOCSP-39082 to v1.21. (#368)

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664224c9cfd4ff22fd1ed5a7)
=> (DOCSP-39465): Backport DOCSP-39082 to v1.20. (#368)

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6642264acfd4ff22fd1f8b1b)
=> (DOCSP-39467): Backport DOCSP-39082 to v1.18. (#368)

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664226f2cfd4ff22fd1fc65b)
=> (DOCSP-39468): Backport DOCSP-39082 to v1.17. (#368)

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6642279ccfd4ff22fd1ffeac)
=> (DOCSP-39469): Backport DOCSP-39082 to v1.16. (#368)

snooty.toml, source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66422910cfd4ff22fd2078e4)
=> (DOCSP-39470): Backport DOCSP-39082 to v1.15. (#368)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66422aa6cfd4ff22fd211afa)
=> (DOCSP-39471): Backport DOCSP-39082 to v1.14. (#368)

source/reference/json.txt, source/reference/json/connected-org-config-file.txt
- [DOCSP-39284](https://jira.mongodb.org/browse/DOCSP-39284)
- STAGING:
- [Federated Authentication Configuration File](https://preview-mongodberabilmdb.gatsbyjs.io/atlas-cli/DOCSP-39284/reference/json/connected-org-config-file/)
- [JSON Configuration Files](https://preview-mongodberabilmdb.gatsbyjs.io/atlas-cli/DOCSP-39284/reference/json/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e1742cf5bec1c29b9c431)
=> (DOCSP-39284) Adds example config for federated auth connected orgs.

source/reference/json.txt, source/reference/json/connected-org-config-file.txt
Backports #379 
[Jira](https://jira.mongodb.org/browse/DOCSP-39284) 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e22c7cf5bec1c29bdd48d)
=> Backports DOCSP-39284 to v1.22

source/atlas-cli-deploy-docker.txt
- [DOCSP-40213](https://jira.mongodb.org/browse/DOCSP-40213)
- [STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-40213/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66635d0debce19f314f00b53)
=> (DOCSP-40213): Fixed deploymenets typo.

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66635f7eebce19f314f10ed8)
=> (DOCSP-40310): Backport DOCSP-40213 to v1.23. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6663602bebce19f314f18619)
=> (DOCSP-40311): Backport DOCSP-40213 to v1.22. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666360c3ebce19f314f1c7fb)
=> (DOCSP-40312): Backport DOCSP-40213 to v1.21. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666361b3ebce19f314f223e8)
=> (DOCSP-40313): Backport DOCSP-40213 to v1.20. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66636252ebce19f314f255d3)
=> (DOCSP-40314): Backport DOCSP-40213 to v1.19. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666362f2ebce19f314f2c1e5)
=> (DOCSP-40315): Backport DOCSP-40213 to v1.18. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666364bfebce19f314f36e9d)
=> (DOCSP-40316): Backport DOCSP-40213 to v1.17. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66636749ebce19f314f45964)
=> (DOCSP-40317): Backport DOCSP-40213 to v1.16. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666367d9ebce19f314f48736)
=> (DOCSP-40318): Backport DOCSP-40213 to v1.15. (#382)

source/atlas-cli-deploy-docker.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6663687aebce19f314f4b71e)
=> (DOCSP-40319): Backport DOCSP-40213 to v1.14. (#382)

snooty.toml
Updated version used on installation page from 6.0 to 7.0 in the Yum and Apt tabs.
Will backport all the way to v1.21 after this PR is approved and merged.
- [DOCSP-39200](https://jira.mongodb.org/browse/DOCSP-39200)
- [STAGING](https://preview-mongodbkyuanmongodb.gatsbyjs.io/atlas-cli/DOCSP-39200/install-atlas-cli/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c525aebce19f314554fc4)
=> DOCSP-39200 updated version on installation page

source/images/hero.svg, source/index.txt
- [DOCSP-40469](https://jira.mongodb.org/browse/DOCSP-40469)
- [STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/atlas-cli/docsworker-xlarge/DOCSP-40469/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c78faebce19f3146221e9)
=> (DOCSP-40469) Updated the Overview Images for Dark Mode

snooty.toml
@melissamahoney-mongodb, I'm moving v1.6 to the Legacy site.
- [DOCSP-40964](https://jira.mongodb.org/browse/DOCSP-40964)
- [STAGING](https://preview-mongodbcorryroot.gatsbyjs.io/atlas-cli/DOCSP-40964/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667d70c5ebce19f31496888d)
=> (DOCSP-40964): Moving v1.6 to the Legacy site.

snooty.toml
(cherry picked from commit 3104cfb8000f1a630cc360c6ac343705fc436ba1)
Backporting #395 
- [DOCSP-39200r](https://jira.mongodb.org/browse/DOCSP-39200)
- [STAGING](https://preview-mongodbkyuanmongodb.gatsbyjs.io/atlas-cli/DOCSP-39200-v124/install-atlas-cli/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667d885bebce19f314a1dbb1)
=> DOCSP-39200 updated version on installation page (#395)

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.23
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.23/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667dab81ebce19f314ae185b)
=> Backport DOCSP-40123 to v1.23

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.24
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.24/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667dadf5fe162e5006c03802)
=> Backport DOCSP-40123 to v1.24

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.22
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.22/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667daf19fe162e5006c0cecd)
=> Backport DOCSP-40123 to v1.22

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.21
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.21/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667dafb0fe162e5006c10089)
=> Backport DOCSP-40123 to v1.21

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.20
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.20/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db08cfe162e5006c14cd2)
=> Backport DOCSP-40123 to v1.20

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.19
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.19/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db124fe162e5006c18d3d)
=> Backport DOCSP-40123 to v1.19

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.18
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.18/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db1b6fe162e5006c1e241)
=> Backport DOCSP-40123 to v1.18

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.17
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.17/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db25efe162e5006c22191)
=> Backport DOCSP-40123 to v1.17

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.16
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.16/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db2f6fe162e5006c2695b)
=> Backport DOCSP-40123 to v1.16

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.15
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.15/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db379fe162e5006c29ab9)
=> Backport DOCSP-40123 to v1.15

source/atlas-cli-deploy-docker.txt
Backport DOCSP-40123 to v1.14
- [STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/atlas-cli/DOCSP-40123v1.14/atlas-cli-deploy-docker/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667db411fe162e5006c2c88a)
=> Backport DOCSP-40123 to v1.14

source/compatibility.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668d84fbfb8bd13b847f5af9)
=> (DOCSP-38876) Updates MacOS compatibility (#361)

snooty.toml
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-41442)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-41442-v1.8/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6691281efb8bd13b84514ad6)
=> (DOCSP-41442) Archives Atlas CLI version 1.8

snooty.toml
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-41442)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-41442-v1.7/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669127f5fb8bd13b8451416e)
=> (DOCSP-41442) Archives Atlas CLI version 1.7

snooty.toml
Reverts mongodb/docs-atlas-cli#448
=> Revert "(DOCSP-41442) Archives Atlas CLI version 1.8"

snooty.toml
Reverts mongodb/docs-atlas-cli#449
=> Revert "(DOCSP-41442) Archives Atlas CLI version 1.7"

snooty.toml
- [DOCSP](https://jira.mongodb.org/browse/DOCSP-41442)
- [STAGING](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/DOCSP-41442-v1.7-2/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66916410fb8bd13b84607594)
=> Archives version 1.7

source/atlas-cli-changelog.txt, source/atlas-cli-ephemeral-cluster.txt
Backports #447 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66917d45fb8bd13b846ac8a6)
=> (DOCSP-41222) Resolves quickstart build warnings (#447)

.gitmodules, source/command
This will only be implemented on the test-copybara branch for the time being
[Staging](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/test-copybara-1/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669fe1c726eba79552794a35)
=> Removes submodule

source/command/test.txt
[Staging](https://preview-mongodbsarahsimpers.gatsbyjs.io/atlas-cli/test-copybara-2/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669fe2da26eba7955279a07f)
=> Adds back the command dir, test file

build.sh, netlify.toml
=> Adds netlify files (#472)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c601fe40f3e3c873e9cfe1)
=> (DOCSP-42799): Backport DOCSP-41388 to v1.24. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c6037f40f3e3c873ea5c20)
=> (DOCSP-42801): Backports DOCSP-41388 to v1.22. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c609be40f3e3c873ebeee1)
=> (DOCSP-42802): Backports DOCSP-41388 to v1.21. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60a8d40f3e3c873ec4737)
=> (DOCSP-42803): Backports DOCSP-41388 to v1.20. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60b8540f3e3c873ec8a57)
=> (DOCSP-42804): Backports DOCSP-41388 to v1.19. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60c2b40f3e3c873ece271)
=> (DOCSP-42805): Backports DOCSP-41388 to v1.18. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60ce440f3e3c873ed425a)
=> (DOCSP-42806): Backports DOCSP-41388 to v1.17. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60d8b40f3e3c873ed772b)
=> (DOCSP-42807): Backports DOCSP-41388 to v1.16. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60e5140f3e3c873edb679)
=> (DOCSP-42808): Backports DOCSP-41388 to v1.15. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60f0140f3e3c873edeb7d)
=> (DOCSP-42809): Backports DOCSP-41388 to v1.14. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c60fe740f3e3c873ee2bfb)
=> (DOCSP-42810): Backports DOCSP-41388 to v1.13. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c6108b40f3e3c873ee5df0)
=> (DOCSP-42811): Backports DOCSP-41388 to v1.12. (#536)

source/install-atlas-cli.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c6113840f3e3c873ee9146)
=> (DOCSP-42812): Backports DOCSP-41388 to v1.11. (#536)

source/compatibility.txt, source/install-atlas-cli.txt
=> DOCSP-41017 Remove support for Debian 10, RHEL 7.0, and Amazon 2

source/command/atlas-deployments-connect.txt, source/command/atlas-deployments-setup.txt, source/command/atlas-plugin-install.txt, source/command/atlas-plugin-list.txt, source/command/atlas-plugin-uninstall.txt, source/command/atlas-plugin-update.txt, source/command/atlas-plugin.txt, source/command/atlas.txt
Copies Atlas CLI commands from the source repo. See the attached Netlify comment for build log and staging.
=> Copies Atlas CLI commands for release tag: atlascli/v1.27.0

source/atlas-cli-deploy-fts.txt
- [DOCSP-42908](https://jira.mongodb.org/browse/DOCSP-42908)
- [STAGING](https://preview-mongodbkanchanamongodb.gatsbyjs.io/atlas-cli/DOCSP-42908/atlas-cli-deploy-fts/)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66cf7652c87522bd3a4641dd)
=> DOCSP-42908 Document localdev restrictions

snooty.toml
https://deploy-preview-642--docs-atlas-cli.netlify.app/command/atlas-deployments-connect/
=> add banner to local deployment pages

source/command/atlas-performanceAdvisor-slowQueryLogs-list.txt
(cherry picked from commit 33941971b70f148c5e9cf20b086a7c6ae10a99b8)
Backporting #663 
- [DOCSP-43449](https://jira.mongodb.org/browse/DOCSP-43449)
- [STAGING](https://deploy-preview-665--docs-atlas-cli.netlify.app/command/atlas-performanceAdvisor-slowQueryLogs-list/#options)
=> DOCSP-43449 updated text for nLogs param

source/command/atlas-performanceAdvisor-slowQueryLogs-list.txt
(cherry picked from commit 33941971b70f148c5e9cf20b086a7c6ae10a99b8)
Backporting #663 
- [DOCSP-43449](https://jira.mongodb.org/browse/DOCSP-43449)
- [STAGING](https://deploy-preview-667--docs-atlas-cli.netlify.app/command/atlas-performanceAdvisor-slowQueryLogs-list/#options)
=> DOCSP-43449 updated text for nLogs param 

source/command/atlas-performanceAdvisor-slowQueryLogs-list.txt
(cherry picked from commit 33941971b70f148c5e9cf20b086a7c6ae10a99b8)
Backporting #663 
- [DOCSP-43449](https://jira.mongodb.org/browse/DOCSP-43449)
- [STAGING](https://deploy-preview-671--docs-atlas-cli.netlify.app/command/atlas-performanceAdvisor-slowQueryLogs-list/#options)
=> DOCSP-43449 updated text for nLogs param (#663)

source/command/atlas-dbusers-create.txt, source/command/atlas-dbusers-update.txt
Copies Atlas CLI commands from the source repo. See the attached Netlify comment for build log and staging.
=> Copies Atlas CLI commands for release tag: atlascli/v1.29.0

snooty.toml, source/atlas-cli-deploy-local.txt, source/atlas-cli-local-cloud.txt, source/atlas-cli-tutorials.txt, source/includes/fact-atlas-deployments-preview.rst, source/includes/fact-deploy-tutorial-prereqs.rst, source/telemetry.txt
Add supported operating systems and architectures for local deployment of Atlas
NOTE: I've combined the required changes from https://jira.mongodb.org/browse/DOCSP-43126 with this PR. 
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-43519)
- [STAGING](https://deploy-preview-676--docs-atlas-cli.netlify.app/atlas-cli-deploy-local/#supported-os-for-local-atlas-deployments)
=> DOCSP-43519 -- Add supported operating systems and architectures for local deployment of Atlas

source/atlas-cli-env-variables.txt
[This spreadsheet](https://docs.google.com/spreadsheets/d/1M2IlsyV0-6mY-AvBBrX-4uSDtQrbt9zuoXsqIJaVqlk/edit?gid=0#gid=0) tracks the number of nested components on each page, and [this doc](https://docs.google.com/document/d/1yMbng-EPOQ82bAzBTC2VJwIvsUBOSCJh21cGbDoe1a8/edit#heading=h.7hxlffls9cx6)  provides guidelines for fixing nested components.
=> (DOCSP-42975) [Atlas CLI] Atlas CLI nested components

source/compatibility.txt
- [DOCSP-40006](https://jira.mongodb.org/browse/DOCSP-40006)
=> (DOCSP-40006) updates compatibility matrix for ubuntu 24.04

source/atlas-cli-deploy-docker.txt
Backport to v1.29
- [DOCSP-number](https://jira.mongodb.org/browse/44181)
=> DOCSP-44181 -- Backport to v1.29

source/atlas-cli-deploy-docker.txt
Remove public preview banner
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-44181)
- [STAGING](https://deploy-preview-706--docs-atlas-cli.netlify.app/atlas-cli-deploy-docker/)
=> DOCSP-44181 -- remove public preview banner

source/atlas-cli-changelog.txt, source/troubleshooting.txt
* updated troubleshooting page with podman error
(cherry picked from commit 193caa29473dd81e0ef4d62107cd0ae39badccf1)
Backporting #708 
- [DOCSP-42444](https://jira.mongodb.org/browse/DOCSP-42444)
=> DOCSP-42444 updated troubleshooting page with podman error

source/atlas-cli-tutorials.txt, source/connect-atlas-cli.txt, source/index.txt, source/install-atlas-cli.txt
Updating the Atlas CLI ToC based on the new style guide requirements: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/
- [DOCSP-44126](https://jira.mongodb.org/browse/DOCSP-44126)
- [STAGING](https://deploy-preview-709--docs-atlas-cli.netlify.app)
=> DOCSP-44126-ToC-Refactor

source/atlas-cli-deploy-local.txt, source/includes/fact-deploy-tutorial-prereqs.rst, source/includes/steps-atlas-cli-deploy-local-prereqs.rst
Updates prerequisites to more closely match the [vector search local dev](https://www.mongodb.com/docs/atlas/atlas-vector-search/tutorials/vector-search-quick-start) procedure.
- [DOCSP-43903](https://jira.mongodb.org/browse/DOCSP-43903)
- [STAGING](https://deploy-preview-757--docs-atlas-cli.netlify.app/atlas-cli-deploy-local/)
=> (DOCSP-43903): Update local dev setup instructions

source/atlas-cli-deploy-local.txt, source/includes/fact-deploy-tutorial-prereqs.rst, source/includes/steps-atlas-cli-deploy-local-prereqs.rst
- [DOCSP-45130](https://jira.mongodb.org/browse/DOCSP-45130)
=> (DOCSP-45130): Backport DOCSP-43903 to current

source/atlas-cli-deploy-docker.txt
- [DOCSP-45098](https://jira.mongodb.org/browse/DOCSP-45098)
- [STAGING](https://deploy-preview-760--docs-atlas-cli.netlify.app/atlas-cli-deploy-docker/#persist-data-across-runs-with-docker-compose)
=> (DOCSP-45098) Updates localdev Docker compose example.

source/atlas-cli-deploy-docker.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45098)
Backports https://github.com/mongodb/docs-atlas-cli/pull/760
=> Backports DOCSP-45098 to v1.29

source/atlas-cli-deploy-docker.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-45098)
Backports #760
=> Backports DOCSP-45098 to v1.30

source/atlas-cli-changelog.txt
- [DOCSP-45775](https://jira.mongodb.org/browse/DOCSP-45775)
- [Release Notes for 1.33](https://deploy-preview-782--docs-atlas-cli.netlify.app/atlas-cli-changelog/)
Hi Sarah, do I need to review RelNotes with anyone from the dev team? Thank you for your review.
=> (DOCSP-45775) Release notes for 1.33

source/connect-atlas-cli.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-38083)
=> (DOCSP-38083) Deprecate blacklist and whitelist terminology.

source/atlas-cli-deploy-docker.txt, source/atlas-cli-deploy-local.txt, source/includes/fact-installation-workaround-m4chips.rst
- [STAGING](https://deploy-preview-809--docs-atlas-cli.netlify.app/atlas-cli-deploy-docker/)
=> (DOCSP-46401) Adds install workaround for m4 chips.

source/atlas-cli-deploy-docker.txt, source/atlas-cli-deploy-local.txt, source/includes/fact-installation-workaround-m4chips.rst
Backports #809
[Jira](https://jira.mongodb.org/browse/DOCSP-46401)
=> Backports DOCSP-46401 to v1.25

source/atlas-cli-changelog.txt, source/atlas-cli-deploy-fts.txt, source/atlas-cli-deploy-local.txt
- [DOCSP-45602](https://jira.mongodb.org/browse/DOCSP-45602)
- STAGING
- https://deploy-preview-806--docs-atlas-cli.netlify.app/atlas-cli-changelog
- https://deploy-preview-806--docs-atlas-cli.netlify.app/atlas-cli-deploy-fts
- https://deploy-preview-806--docs-atlas-cli.netlify.app/atlas-cli-deploy-local
=> DOCSP-45602 fix CLI page links to KNN beta

source/atlas-cli-changelog.txt
- [DOCSP-47205](https://jira.mongodb.org/browse/DOCSP-47205)
=> (DOCSP-47205) Fixes build errors.

source/atlas-cli-deploy-docker.txt, source/atlas-cli-deploy-local.txt, source/includes/fact-installation-workaround-m4chips.rst
Backports #875 
[DOCSP-47165](https://jira.mongodb.org/browse/DOCSP-47165)
=> Backports DOCSP-47165 to v1.25

source/includes/steps-run-as-daemon.rst, source/includes/steps-run-interactive-mode.rst, source/troubleshooting.txt
- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-46527)
- [STAGING](https://deploy-preview-885--docs-atlas-cli.netlify.app/troubleshooting/#failed-to-install-atlascli-plugin)
=> Docsp 46527 -- Add Troubleshooting entry

config/redirects, source/index.txt, source/plugin-changelogs, source/plugin-changelogs.txt
- [STAGING](https://deploy-preview-956--docs-atlas-cli.netlify.app/plugin-changelogs/)
=> add ak8so plugin changelog

source/reference/json/search-index-config-file.txt
- [DOCSP-48344](https://jira.mongodb.org/browse/DOCSP-48344)
- [STAGING](https://deploy-preview-971--docs-atlas-cli.netlify.app/reference/json/search-index-config-file/)
=> DOCSP-48344 fix api link for update Search Index

snooty.toml, source/atlas-cli-admin-api.txt, source/atlas-cli-tutorials.txt
- [DOCSP-48672](https://jira.mongodb.org/browse/DOCSP-48672)
- [STAGING](https://deploy-preview-982--docs-atlas-cli.netlify.app/atlas-cli-admin-api/)
=> DOCSP-48672 Document API Access

source/atlas-cli-changelog.txt
Add release notes for 1.42.1 
- [DOCSP-49535](https://jira.mongodb.org/browse/DOCSP-49535)
- [STAGING](https://deploy-preview-988--docs-atlas-cli.netlify.app/atlas-cli-changelog/)
=> [DOCSP-49535] AtlasCLI 1.42.1 Release Notes

.github/prompts/eol-branch.prompt.md, .gitignore
=> add sunset version prompt

.github/prompts/eol-branch.prompt.md
=> update sunsetting prompt

.github/prompts/eol-branch.prompt.md
=> prompt fix

.github/prompts/eol-branch.prompt.md
=> final fix to prompt

source/compatibility.txt
- [DOCSP-48014](https://jira.mongodb.org/browse/DOCSP-48014)
- [STAGING](https://deploy-preview-1104--docs-atlas-cli.netlify.app/compatibility/)
=> DOCSP-48014 Update AtlasCLI compatibility matrix

.backportrc.json
- [DOCSP-50349](https://jira.mongodb.org/browse/DOCSP-50349)
=> (DOCSP-50349) Removes v1.37 from backport tool.
